### ISSUE TITLE
CassandraStatement.getMoreResults throws SQLRecoverableException; Solr can't deal with it.

### ISSUE THREAD

**Issue by Nexolight** [adejanovski/cassandra-jdbc-wrapper#14]
This happens with solr 6.3 at the very end of a huge dataimport.

```
getNext() failed for query 'select * from mykeyspace.mytable':org.apache.solr.handler.dataimport.DataImportHandlerException: java.sql.SQLRecoverableException: method was called on a closed Statement
	at org.apache.solr.handler.dataimport.DataImportHandlerException.wrapAndThrow(DataImportHandlerException.java:61)
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.hasnext(JdbcDataSource.java:464)
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator$1.hasNext(JdbcDataSource.java:377)
	at org.apache.solr.handler.dataimport.EntityProcessorBase.getNext(EntityProcessorBase.java:133)
	at org.apache.solr.handler.dataimport.SqlEntityProcessor.nextRow(SqlEntityProcessor.java:75)
	at org.apache.solr.handler.dataimport.EntityProcessorWrapper.nextRow(EntityProcessorWrapper.java:244)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:475)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:414)
	at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:329)
	at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:232)
	at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:416)
	at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:475)
	at org.apache.solr.handler.dataimport.DataImporter.lambda$runAsync$0(DataImporter.java:458)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLRecoverableException: method was called on a closed Statement
	at com.github.adejanovski.cassandra.jdbc.CassandraStatement.checkNotClosed(CassandraStatement.java:137)
	at com.github.adejanovski.cassandra.jdbc.CassandraStatement.getMoreResults(CassandraStatement.java:329)
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.hasnext(JdbcDataSource.java:458)
```

Solr can't deal with that exception.

**Comment by Nexolight** [comment]
There are a few more problems when using this wrapper for the solr data import handler.
I had not any time to investigate more but on my fork@solr_dih are two commits which solved all the problems I had. At least it works as desired.

Even when this execptions would not be critical they break the dataimport for solr 6.30 (latest).
I guess this dirty fixes work because it doesn't really matter in the implementation at the very end.

The behavoir of this wrapper is like it's documented for other jdbc drivers. So it's more likely an issue in the solr dataimporthandler library. You may close that issue.

**Comment by adejanovski** [comment]
Thanks for the update. 

Closing
