### ISSUE TITLE
Cassandra JDBC write with "Cassandra implementation is always in auto-commit mode" exception

### ISSUE THREAD

**Issue by RahulJyala7** [adejanovski/cassandra-jdbc-wrapper#26]
WARNING: An internal object pool swallowed an Exception.
java.sql.SQLFeatureNotSupportedException: the Cassandra implementation is always in auto-commit mode
	at com.github.adejanovski.cassandra.jdbc.CassandraConnection.rollback(CassandraConnection.java:379)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:492)

**Comment by RahulJyala7** [comment]
also prints "Datacenter: %s; Host: %s; Rack: %s" when connection created
