### ISSUE TITLE
Dbeaver Community - Connects OK, but accessing "tables" results in Caused by: java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [adejanovski/cassandra-jdbc-wrapper#32]
Latest DBEAVER Community Edition 6.3.2
Latest cassandra-jdbc-wrapper 3.1.0 (full fat pre-bake jar)

Connects fine, and see keyspaces and "tables", but when trying to access the table properties or data:

org.jkiss.dbeaver.DBException: null
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:209)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3434)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at com.github.adejanovski.cassandra.jdbc.MetadataRow.getInt(MetadataRow.java:119)
	at com.github.adejanovski.cassandra.jdbc.MetadataRow.getInt(MetadataRow.java:124)
	at com.github.adejanovski.cassandra.jdbc.CassandraMetadataResultSet.getInt(CassandraMetadataResultSet.java:503)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getInt(JDBCResultSetImpl.java:485)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetInt(JDBCUtils.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericUtils.safeGetInt(GenericUtils.java:84)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:149)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:149)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readRequiredMeta(JDBCTable.java:922)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:130)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
	... 4 more

**Comment by sabarish1150** [comment]
Hi Iam also facing the same issue. Is there any workaround for this issue.

Thanks
Sabarish

**Comment by hunghx12** [comment]
Same issue here. Have to use queries instead of using GUI.

**Comment by AbrahamNuno** [comment]
Any update about this?

I have the same issue since last year and I haven't been able to fix it or workaround it.

DBeaver Community version: 7.1.5.202008170457

**Comment by lijunyong** [comment]
https://www.cdata.com/kb/tech/cassandra-jdbc-dbvr.rst  it's work for me
